### ISSUE TITLE
Bug: If a question is first retagged then edited silently, the "time" links to the edits page

### ISSUE THREAD

**Issue by gurjyot** [svivian/q2a-edit-history#17] opened 2015-06-19 20:34 UTC
If a question is retagged and after some time it is edited silently. Then it says {retagged "time" ago by user_name}. And the time is linked to the edits page which should not be storing the edits.

**Comment by svivian** [comment] 2015-07-28 23:28
Duplicate of #15. Doing some work on my plugins this week so I'll try and fix this soon.

**Closed** 2015-07-29 00:00 UTC
